// @ts-nocheck -- ported from the (non-strict) Lovify app repo; web2app funnel code
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Whether real Supabase credentials were provided at build time. When they're
// missing (e.g. a preview build that didn't get the env vars), we must NOT let
// createClient throw — that error is thrown at import time and white-screens
// the entire app. Instead we boot with inert placeholders so the UI still
// renders; any actual backend call simply fails gracefully at runtime.
export const supabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!supabaseConfigured) {
  // Surface it loudly in the console for whoever is debugging the deploy,
  // without taking the whole page down.
  console.error(
    '[supabase] Missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'Booting with a placeholder client — auth and data calls will not work ' +
    'until these env vars are set for this environment.'
  );
}

// A syntactically-valid but non-functional fallback so createClient never
// throws. It points nowhere real, so requests just error out at runtime.
const FALLBACK_URL = 'https://placeholder.supabase.co';
const FALLBACK_KEY = 'public-anon-placeholder';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);